### PR TITLE
Add test coverage for CLI module

### LINKED ISSUE #4: Add test coverage for CLI module
The CLI module needs to have full test coverage.  We have seen a couple of bugs related to the fact that we don't have coverage for it.  Should also consider porting it to TS as well.

### PR DESCRIPTION
**Pull request by mkantor**
Extract CLI helper functions to a lib, add tests, and port it to TS.

Fixes #4

### CODE REVIEW

**Comment by mkantor** [comment]
I'm not sure what this CI failure is about:

```
$ npm install graphql
npm WARN package.json @creditkarma/graphql-validator@0.3.0 No repository field.
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.8.3/bin/node" "/home/travis/.nvm/versions/node/v4.8.3/bin/npm" "install" "graphql"
npm ERR! node v4.8.3
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package graphql@0.10.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @creditkarma/graphql-loader@0.3.0 wants graphql@^0.9.0
npm ERR! peerinvalid Peer graphql-tools@0.11.0 wants graphql@^0.8.0 || ^0.9.0 || ^0.10.0
```

I'm able to run `npm install` locally with a fresh environment without problems. Perhaps it has to do with a difference in versions; I'm using node v7.10.0 with npm v4.2.0.

Off to read about peer dependencies...

---

**UPDATE:** Everything works on my machine using node v4.8.3 as well. I'm not sure what's different about the CI environment.

---

**UPDATE 2:** I just realized that [the Travis config separately installs the `graphql` package without any version constraint](https://github.com/creditkarma/graphql-validator/blob/89dedf33ad9122b4b8a74a23761fa0192eebccc9/.travis.yml#L8). `graphql`  v0.10.x was published recently, so now Travis is installing that one, and it doesn't line up with the constraints in package.json (`"graphql": "^0.9.0"`). A CI build of master would hit the same problem.

I'm not sure why the `graphql` package is marked as a peer dependency instead of a normal dependency. I see this was changed in #3, but [`index.ts` directly imports stuff from `graphql`](https://github.com/creditkarma/graphql-validator/blob/89dedf33ad9122b4b8a74a23761fa0192eebccc9/src/index.ts#L3), which makes me think it should be a normal dependency. This is my first exposure to peer dependencies in npm though, so I could be missing something.

I can see three ways to fix this; let me know which sounds best and I'll open another PR:

1. Change the Travis config to install a compatible version of the `graphql` package (`^0.9.0`).
1. Change the version constraints in package.json to be more lenient about what versions of `graphql` are acceptable (this would require testing and also a similar change in the `graphql-loader` package).
1. Revert part of #3, putting `graphql` back into the normal dependency list and removing the Travis config to install it separately.

---

**UPDATE 3:** I opened #11 about the peer dependency issue, since it's not directly related to my changes in this pull request.

**Comment by nnance** [comment]
@mkantor I like your changes and would like to merge but is failing some tests.  mind fixing them?

**Comment by mkantor** [comment]
@nnance looks like you fixed #11, which was the cause of the CI failures. I rebased my branch and now all is green.

**Comment by nnance** [comment]
@mkantor thanks for the help.  really like the improvement!

**Pull request merged**
